# Generated by Django 5.2 on 2025-04-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'ANDROID'), (1, 'WEB'), (2, 'IOS')], default=1),
        ),
    ]
